name : This is AI workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - main


jobs:
  check-release-version:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name : Set environment variable
        run: |
          echo "MERGE_SHA=${{ github.event.pull_request.merge_commit_sha }}" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=release/v1.0" >> $GITHUB_ENV
          echo "FEATURE_BRANCH=feature/release-v1.0" >> $GITHUB_ENV

      - name : Fetch all branches
        run: |
          git fetch origin


      - name: Check release branch
        run: |

          echo "Checking release branch: $RELEASE_BRANCH"

          if git ls-remote --heads origin $RELEASE_BRANCH | grep $RELEASE_BRANCH
          then
            echo "Release branch exists"
          else
            echo "ERROR: Release branch does not exist"
            exit 1
          fi

      - name: Create release feature branch
        run: |

          echo "Creating branch: $FEATURE_BRANCH"

          git checkout -b $FEATURE_BRANCH origin/$RELEASE_BRANCH

          echo "Current branch:"
          git branch

      - name: Cherry pick merge commit
        run: |

          echo "Cherry picking commit:"
          echo $MERGE_SHA

          git cherry-pick -m 1 $MERGE_SHA
        # Push generated branch
      - name: Push release feature branch
        run: |

          echo "Pushing branch: $FEATURE_BRANCH"

          git push origin $FEATURE_BRANCH

     
